[package]
name = "rustine-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rustine = { path = "..", default-features = false }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_lex"
path = "fuzz_targets/fuzz_lex.rs"
doc = false

[[bin]]
name = "fuzz_parse"
path = "fuzz_targets/fuzz_parse.rs"
doc = false

[[bin]]
name = "fuzz_execute"
path = "fuzz_targets/fuzz_execute.rs"
doc = false
